export const ButtonBaseProps = {
	label: null,
	icon: null,
	iconPos: 'left',
	badge: null,
	severity: null,
	rounded: false,
	raised: false,
	outlined: false,
	text: false,
	link: false,
	badgeClassName: null,
	tooltip: null,
	size: null,
	tooltipOptions: null,
	disabled: false,
	loading: false,
	loadingIcon: 'pi pi-spinner pi-spin',
	visible: true,
}
